[package]
name = "chess2"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.10.1", features = ["dynamic_linking", "jpeg"] }
ndarray = "0.15.6"

[profile.dev]
opt-level = 3

[profile.dev.package."*"]
opt-level = 3
