[build]
# target = "wasm32-unknown-unknown"
target = "x86_64-unknown-linux-gnu"
# target = "x86_64-pc-windows-msvc"

[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
rustflags = ["-Z", "share-generics=y"]